Add production modifier to apiary hud, add magic apiary to forestry handler
GTNewHorizons/WAILAPlugins pull request #16
Opened 2023-08-27 01:49 UTC by hacatu

Apiary, bee house, alveary, and magic apiary will now include `Effective production: b^0.52 * %s` in their waila hud, giving a quick overview of how much effect the current production modifier is actually having.  I also added this functionality to the industrial apiary but that handles its own waila hud, it doesn't go through the plugins mod.

`spotlessApply` and `updateDependencies` changed a lot of unrelated files so let me know if I need to redo this PR

2023-08-27 01:51 UTC, hacatu commented
![Example tooltip in my testing world](https://github.com/GTNewHorizons/WAILAPlugins/assets/4614167/ec97d94a-013f-465f-b960-277d97c0731e)

2023-08-27 04:09 UTC, hacatu commented
The effective production reported for alvearies with electrical stimulators seems to be incorrect, which is really weird because it does seem to take into account frame housings.  My first guess was it's because extrabees replaces the alveary tile entity but then it wouldn't change when I added frame housings.  So unfortunately I'll have to look into that

2023-08-29 02:50 UTC, hacatu commented
Fixed - it was just a simple issue of me accidentally doing some calculations clientside instead of serverside due to not fully understanding waila.

I also moved the "Effective Production" section to be after the drone section, so it doesn't split apart the queen and drone sections in the hud.

2023-09-16 12:46 UTC, kuba6000 requested changes

2023-09-16 12:46 UTC, kuba6000 commented on src/main/java/tterrag/wailaplugins/plugins/PluginForestry.java
> +@Plugin(name = "Forestry", deps = { "Forestry", "MagicBees" })
It would be better to add it as an optional dep, so the mod loads without Magic Bees

2023-09-16 19:19 UTC, kuba6000 requested changes

2023-09-16 19:19 UTC, kuba6000 commented on src/main/java/tterrag/wailaplugins/plugins/PluginForestry.java
> +            IBeeHousing housing = (IBeeHousing) tile;
Unused variable?

2023-09-16 21:25 UTC, kuba6000 approved these changes

2023-09-16 21:25 UTC, merged